<menu>
<h1><a href="https://helios.vse.gmu.edu/~smille78/IT207/">Home Page</a></h1>

<p><b>Lab Assignments</b> </p>
<a href="https://helios.vse.gmu.edu/~smille78/IT207/Lab1/">Lab 1</a>
<br>
<a href="https://helios.vse.gmu.edu/~smille78/IT207/Lab2/">Lab 2</a>
<br>
<a href="https://helios.vse.gmu.edu/~smille78/IT207/Lab3/">Lab 3</a>
<br>
<a href="https://helios.vse.gmu.edu/~smille78/IT207/Lab4/">Lab 4</a>
<br>
<p><b>Practica</b></p>
<br>
<a href="https://helios.vse.gmu.edu/~smille78/IT207/BP1/">Practicum 1</a>
<br>
<a href="https://helios.vse.gmu.edu/~smille78/IT207/BP2/">Practicum 2</a>
</menu>